config/routes.rb
# better yet, just don't let people use . as part of a username.
# # by default rails considers '.' a separator, so override that
# module ActionController::Routing
#   SEPARATORS = %w( / ? )
# end

Rails.application.routes.draw do

  root to: "home#index"

  devise_for :users, controllers: { registration: 'registrations', session: 'sessions', invitations: 'users/invitations' }

  resources :tsts, path: :tests, as: :tests do
    member do
      get :publish
      get :enable
      get :disable
      get :comments
      get :results
    end
    resources :questions do
      collection do
        post :update_positions
      end
      member do
        post :answer
      end
    end
  end
  match 'tests/:test_id/invite', :to => 'devise/invitations#new', :as => 'test_invite', :via => :get
  match 'tests/:id/:permalink/results/:user_id/:take', :to => 'tsts#individual_results', :as => 'individual_test_results', :via => :get

  match 'people/:id/tests', :to => 'people#tests', :as => 'person_tests', :via => :get
  match 'people/:id/:slug', :to => 'people#show', :as => 'person', :via => :get

  match 'people/:id/follow/:object_type/:object_id', :to => 'people#follow', :as => 'follow', :via => :get
  match 'people/:id/unfollow/:object_type/:object_id', :to => 'people#unfollow', :as => 'unfollow', :via => :get

  # resources :users

  match 'embed/:id/:permalink', :to => 'tsts#show', :as => 'embed_test', :via => :get

  # # match 'tests/new', :to => 'tsts#new', :as => 'new_test', :via => :get
  # # match 'tests/:id/edit', :to => 'tsts#edit', :as => 'edit_test', :via => :get

  # match 'tests/:id/enable', :to => 'tsts#enable', :as => 'enable_test', :via => :get
  # match 'tests/:id/disable', :to => 'tsts#disable', :as => 'disable_test', :via => :get
  # match 'tests/:id/invite', :to => 'tsts#invite', :as => 'invite_test', :via => :get
  # # match 'tests/:test_id/questions/new', :to => 'questions#new', :as => 'invite_test', :via => :get
  #
  # match 'tests/:id/:slug', :to => 'tsts#show', :as => 'test', :via => :get
  #
  # # match 'tests/:id/:permalink/start', :to => 'tsts#show', :as => 'test', :via => :get
  #
  # # match 'tests/:id/:permalink', :to => 'tsts#destroy', :as => 'test', :via => :delete
  # # match 'tests/:id/:permalink/questions', :to => 'tsts#questions', :as => 'test_questions', :via => :get
  # # match 'tests/:id/:permalink/questions/:question_id/:qpermalink', :to => 'tsts#show', :as => 'test_question', :via => :get
  # # match 'tests/:id/:permalink/questions/:question_id', :to => 'tsts#show', :via => :get

  resources :results
  # resources :comments

  # match 'search', :to => 'search#results', :as => 'search', :via => :get
  # match 'search/:term', :to => 'search#results', :as => 'search_term', :via => :get

  # match 'tags/:id',:to => 'tags#show', :as => 'tag', :via => :get
  # resources :tags

  # match 'hide_promo', :to => 'home#hide_promo', :as => 'hide_promo', :via => :get

  match 'blohg', :to => 'home#blohg', :as => 'blohg', :via => :get
  match 'about', :to => 'home#about', :as => 'about', :via => :get
  match 'contact', :to => 'home#contact', :as => 'contact', :via => :get
  match 'terms', :to => 'home#terms', :as => 'terms', :via => :get
  match 'notes', :to => 'home#notes', :as => 'notes', :via => :get
  match 'deck', :to => 'home#deck', :as => 'deck', :via => :get
  match 'clear', :to => 'home#clear', :as => 'clear', :via => :get
  # match 'test', :to => 'home#test', :as => 'test'

end

app/models/question.rb
class Question < ApplicationRecord

  TRUEFALSE = 1
  MULTIPLECHOICE = 2
  SHORTANSWER = 3

  # has_friendly_id :name, :use_slug => true
  extend FriendlyId
  friendly_id :name, use: :slugged

  # https://github.com/elight/acts_as_commentable_with_threading
  # acts_as_commentable

  belongs_to :tst
  belongs_to :user
  has_many :choices
  has_many :responses
  has_many :videos

  validates :name, :presence => true
  validates :kind, :presence => true
  validates :tst_id, :presence => true, :numericality => true
  validates :user_id, :presence => true, :numericality => true

  def first?
    ids = tst.questions.pluck(:id)
    (ids.first == self.id) ? true : false
  end

  def last?
    ids = tst.questions.pluck(:id)
    (ids.last == self.id) ? true : false
  end

  def remaining_in_test
    (tst.questions.length - current_position) - 1
  end

  def current_position
    ids = tst.questions.pluck(:id)
    ids.index(self.id)
  end

  def next_question
    return nil if last?
    tst.questions[current_position + 1]
  end

  # total number of times this question has been answered correctly,
  # across all takes. this should probably be stored in the question, so
  # this it doesn't have to do the calculation every time
  def number_correct
    @correct = 0
    responses.each do |r|
      @correct += 1 if r.correct
    end
    @correct
  end

  # if it's a multiple choice question, get the correct one
  def correct_choice
    @_correct_choice ||= begin
      choices.each do |c|
        return c if c.correct?
      end
    end
  end

  def is_multiple_choice
    (kind == Question::MULTIPLECHOICE) ? true : false
  end

  def is_short_answer
    (kind == Question::SHORTANSWER) ? true : false
  end

  # def get_nonzero_position_in_id_array(question_ids)
  #   question_ids.each_with_index do |qid, i|
  #     return i+1 if qid == id
  #   end
  # end

end

app/controllers/questions_controller.rb
# coding: utf-8

class QuestionsController < ApplicationController

  before_action :authenticate_user!, :except => [:index, :show, :answer]

  def update_positions
    question_ids = params[:item_ids].map(&:to_i)
    question_ids_positions = Hash[question_ids.map.with_index.to_a]
    questions = current_user.questions.where(id: question_ids)
    questions.each do |question|
      question.position = question_ids_positions[question.id]
      question.save!
    end
    head :no_content
  end

  def show
    @test = Tst.friendly.find(params[:test_id])
    @owner = true if user_signed_in? && @test.owned_by?(current_user)
    @title = "#{@test.name} - Testeroni"
    @description = "'#{@test.name}' a test on Testeroni.com"

    @question = Question.friendly.find(params[:id])
    # @comment = Comment.new(:commentable_type => @question.class, :commentable_id => @question.id)

    if session[:take_id].present?
      @take = Take.find(session[:take_id])
      @response = Response.where(user: current_user, tst: @test, question: @question, take: @take).first
      @already_taken = Response.where(question: @question, take: @take).present?
    end

    render "tsts/show"
  end


  def answer
    @test = Tst.friendly.find(params[:test_id])
    @question = Question.friendly.find(params[:id])

    # @comment = Comment.new(:commentable_type => @question.class, :commentable_id => @question.id)
    # @take = Take.find_from_session_or_params(params, session)

    if @question.first?
      @take = Take.create!(user: current_user, tst: @test, started_at: Time.now, question_order: @test.questions.pluck(:id))
    elsif session[:take_id].present?
      @take = Take.find(session[:take_id])
    else
      @take = Take.create!(user: current_user, tst: @test, started_at: Time.now, question_order: @test.questions.pluck(:id))
    end

    session[:take_id] = @take.id
    @response = Response.new(user: current_user, tst: @test, question: @question, take: @take)
    # @response.take_id = @take.id if @take.id

    if @question.kind == Question::TRUEFALSE
      @answer = (params[:answer] == 'true') ? 1 : 0
      @response.answer = @answer
      @response.correct = (@answer == @question.correct_response) ? true : false
    elsif @question.kind == Question::MULTIPLECHOICE
      @choice = Choice.find(params[:choice_id])
      @response.choice = @choice
      @response.correct = @choice.correct
    elsif @question.kind == Question::SHORTANSWER
      @response.choice = @question.choices.first
      @response.name = params[:short_answer]
      @response.correct = (Choice.simplify(params[:short_answer]) == @question.choices.first.simple_name) ? true : false
    end
    @response.save!

    @take.questions_answered = @take.questions_answered + 1
    @take.questions_correct = @take.questions_correct + 1 if @response.correct?
    @take.save!

    @response_count = @question.responses.size
    @correct_response_count = @question.number_correct

    @percentage_correct = (@response_count > 0) ? (((@correct_response_count.to_f/@response_count.to_f)*100)+0.5).to_i : 0

    if @question.last?
      @take.finished_at = Time.now
      if user_signed_in?
        record_activity(current_user, Activity::TAKE, @test)
      end
    else
      # @more = true
      @question_ids = @take.question_ids
      # @next_question = Question.friendly.find(@question_ids[params[:question_number].to_i])
      # @next_question_url = question_path(@next_question, :test_id => @test.to_param, :question_number => @next_question_number, :take_id => @take.id)
    end

    @take.save!

    render partial: 'questions/answer'
  end

  def new
    @test = Tst.friendly.find(params[:test_id])
    redirect_to root_path and return unless user_signed_in? && @test.user == current_user

    @question = Question.new
    @title = "New question for '#{@test.name}' - Test"
    @description = "New question for '#{@test.name}' - Test"
  end

  def edit
    @question = Question.friendly.find(params[:id])
    @test = Tst.friendly.find(params[:test_id]) if params[:test_id]
    redirect_to root_path and return unless user_signed_in? && @test.user == current_user

    if @question.kind == Question::SHORTANSWER
      @short_answer = true
    end

    if @question.kind == Question::MULTIPLECHOICE
      @multiple_choice = true
    end
  end

  def create
    @question = Question.new(question_params)
    @test = Tst.friendly.find(params[:test_id]) if params[:test_id]
    redirect_to root_path and return unless user_signed_in? && @test.user == current_user

    @question.tst = @test
    @question.user = current_user

    if params[:question][:correct_response].to_i == Choice::MULTIPLE
      @question.kind = Question::MULTIPLECHOICE
      @question.correct_response = nil
      @saved = @question.save

      # TODO: Dry this; it's repeated in 'update'
      1.upto(Choice::MAX_ALLOWED_CHOICES) do |num|
        @choice = Choice.new
        @choice.question = @question
        @choice.name = params["choice_#{num}".to_sym]
        @choice.correct = (params[:correct_answer] == "choice_#{num}") ? true : false
        @choice.save
      end
    elsif params[:question][:correct_response].to_i == Choice::SHORT
      @question.kind = Question::SHORTANSWER
      @question.correct_response = nil
      @saved = @question.save

      @choice = Choice.new
      @choice.question = @question
      @choice.name = params[:short_answer]
      @choice.simple_name = Choice.simplify(@choice.name)
      @choice.correct = true
      @choice.save
    else
      @question.kind = Question::TRUEFALSE
      @saved = @question.save
    end

    if @saved
      if @test
        flash[:notice] = 'Question added'
        redirect_to(test_path(@test, :a => 'a'))
      else
        redirect_to(@question, :notice => 'Question was successfully created.')
      end
    else
      render :action => "new"
    end
  end

  def update
    @question = Question.friendly.find(params[:id])
    @test = Tst.friendly.find(params[:test_id]) if params[:test_id]
    redirect_to root_path and return unless user_signed_in? && @test.user == current_user

    if @question.update(question_params)

      # handle short answer
      if @question.kind == Question::SHORTANSWER
        @choice = @question.choices.first
        @choice.name = params[:short_answer]
        @choice.simple_name = Choice.simplify(params[:short_answer])
        @choice.save
      end

      # handle multiple choice
      params.each do |param|
        if param[0].include?('choiceupdate_')
          choice = Choice.find(param[0].split('_')[1])
          choice.name = param[1]
          choice.correct = (params[:correct_answer] == param[0]) ? true : false
          choice.save
        end
      end

      if @test
        redirect_to(edit_test_path(@test), :notice => 'Question was successfully updated.')
      else
        redirect_to(@question, :notice => 'Question was successfully updated.')
      end
    else
      render :action => "edit"
    end
  end

  def update_positions
    question_ids = params[:item_ids].map(&:to_i)
    question_ids_positions = Hash[question_ids.map.with_index.to_a]
    questions = current_user.questions.where(id: question_ids)
    questions.each do |question|
      question.position = question_ids_positions[question.id]
      question.save!
    end
    head :no_content
  end

  def destroy
    @question = Question.friendly.find(params[:id])
    redirect_to root_path and return unless user_signed_in? && @question.user == current_user

    @test = Tst.friendly.find(params[:test_id]) if params[:test_id]

    if @question.destroy
      if @test
        redirect_to(edit_test_path(@test), :notice => 'Question was deleted.')
      else
        redirect_to(root_path, :notice => 'Question was deleted.')
      end
    end
  end

  private

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      # params.require(:tst).permit(:name, :description, :status, :contributors)
      params.require(:question).permit(:name, :description, :status, :hint, :image_url, :explanation, :kind, :correct_response, :pause_at)
    end

end

app/helpers/questions_helper.rb
# coding: utf-8
module QuestionsHelper
end

app/views/questions/_answer.html.haml
- classes = ['answer', 'text-white'] # , @question.slug
- classes << ((@response.correct) ? "bg-success" : "bg-danger")

.card-body{class: classes.join(' ')}

  - if @already_taken
    %div
      You already answered, and were

  -if @response.correct
    %h2
      Correct!
  - else
    %h2
      Wrong

    %p
      -if @question.kind == Question::TRUEFALSE
        The correct answer is
        %b
          #{@question.correct_response?}.
      - else
        The correct answer is "#{@question.correct_choice.name}."

  .clearfix

  - if @question.explanation
    #explanation
      = @question.explanation

  -# %div= "#{@correct_response_count} of #{@response_count} people (#{@percentage_correct} percent) answered this correctly"

.card-footer.text-muted

  #progress
    = "You're #{@take.questions_correct} for #{@take.questions_answered}, and "

    -if @question.last?
      done.

    -else
      have #{pluralize(@question.remaining_in_test, 'question')} left

      %div.mt-20
        = link_to "Next question", test_question_path(@test, @question.next_question), class: "btn btn-secondary btn-lg mb-10", style: "font-weight: 300;"

    -# =link_to('all comments', comments_test_path(@test))

  -if @question.last?

    %ul.mt-20
      %li
        Show their score: "You got 76% correct."
      %li
        Show social scoring: "You did better than 34% of the people who've taked this test."
      %li
        Challenge friends to take this test [send invites, track them]
      %li
        Create a team so you can see how everyone in a group does

    %i
      = render partial: "tsts/invite", locals: {test: @question.tst}

app/views/questions/_form.html.haml
-if @test
  %p{:style => "padding:0 0 10px 0;"}
    For the test
    %strong= link_to @test.name, test_path(@test.id, @test.to_param)

-#=form_for test_questions_path(@test) do |f|
= form_with model: @question, url: test_questions_path(@test) do |f|
  =render(:partial => 'application/errors', :locals => {:errors => @question.errors})
  -if params[:test_id]
    %input{:type => "hidden", :name => "test_id", :value => params[:test_id]}

  .actions
    .field
      =f.label :name, 'Question'
      =f.text_field :name, autofocus: true, class: 'form-control'

      %p{:style => "padding:10px 0; margin:3px 0; vertical-align:middle"}
        %p The answer to this question is:
        %p
          =f.radio_button :correct_response, Choice::TRUE
          =f.label "correct_response_#{Choice::TRUE}", 'true', :style => 'display:inline;'
        %p
          =f.radio_button :correct_response, Choice::FALSE
          =f.label "correct_response_#{Choice::FALSE}", 'false', :style => 'display:inline;'
        %p
          =f.radio_button :correct_response, Choice::SHORT, :class => 'short_answer', :checked => (@short_answer) ? 'checked' : 'false'
          =f.label "correct_response_#{Choice::SHORT}", 'short answer', :style => 'display:inline;'
        %p
          =f.radio_button :correct_response, Choice::MULTIPLE, :class => 'multiple_choice', :checked => (@multiple_choice) ? 'checked' : 'false'
          =f.label "correct_response_#{Choice::MULTIPLE}", 'multiple choice', :style => 'display:inline;'


        #short_answers{:style => (@short_answer) ? '' : 'display:none;'}
          %div{:style => 'padding-bottom:10px; margin-bottom:10px; border-bottom: 1px solid #ddd;'}

            .field.mt-20
              %label{for: 'short_answer'}
                Enter a short (less than 10 words) answer
              %input{id: 'short_answer', name: 'short_answer', type: 'text', class: 'form-control', value: (@short_answer) ? @question.choices.first.name : ''}

            %p{:style => 'font-style:italic; padding:5px 0 0 0; width: 70%;'}
              If there is more than one possible correct answer (ie, 'Obama' and 'Barack Obama') you can
              = link_to 'add alternate correct answers.', "#"

        #multiple_choices{:style => (@multiple_choice) ? '' : 'display:none;'}
          %div
            Enter two or more possible answers, and make sure to say which one is correct.
          -if @multiple_choice
            -@question.choices.each_with_index do |choice, i|
              %div
                -# rather than using i+1 for the choice id, should probably use the actual choice.id,
                -# so they can be updated in place.

                %label{:for => "choiceupdate_#{choice.id}"}#{(i+1).ordinalize} choice
                %div
                  -# %input{:id => "choice_#{i+1}", :type => "text", :name => "choice_#{i+1}", :value => choice.name}
                  %input{:id => "choiceupdate_#{choice.id}", :type => "text", :name => "choiceupdate_#{choice.id}", :value => choice.name}
                  %input{:name => "correct_answer", :class => 'correct_answer', :type => "radio", :value => "choiceupdate_#{choice.id}", :checked => (@question.correct_choice.id == choice.id)}
                  correct answer?
          -else
            -1.upto(Choice::MAX_ALLOWED_CHOICES) do |i|
              %div
                %label{:for => "choice_#{i}"}#{i.ordinalize} choice
                %div
                  %input{:id => "choice_#{i}", :type => "text", :name => "choice_#{i}"}
                  -# @multiple_choice
                  %input{:name => "correct_answer", :class => 'correct_answer', :type => "radio", :value => "choice_#{i}"}
                  correct answer?


    .field.mt-20
      =f.label :description, 'Description (shown when the question is asked)'
      =f.text_area :description, style: 'height:60px;', class: 'form-control'

    .field.mt-20
      =f.label :image_url, 'Image URL (optional)'
      =f.text_field :image_url, class: 'form-control'

    .field.mt-20
      =f.label :explanation, 'Explanation (shown after the question is answered)'
      =f.text_area :explanation, style: 'height:60px;display:block;', class: 'form-control'

      -#-unless @test.videos.blank?
        Ask this question
        =f.text_field :pause_at, :style => 'width:20px;'
        seconds into the video.

      .actions
        =f.submit "Save question", class: 'btn btn-outline-dark'

:javascript
  $(document).ready(function(){

    // make sure a correct answer was selected.
    $('#new_question').submit(function() {
      if( $('#question_correct_response_2').is(':checked') ) {

        correct_answer_selected = false;
        $.each( $('.correct_answer'), function() {
          if( $(this).is(':checked') ) {
            correct_answer_selected = true;
          }
        });

        if( correct_answer_selected == false ) {
          alert('Please pick one of your answers as correct.');
          return false;
        }
      }
    });

    $('#question_correct_response_0').click(function() {
      $('#multiple_choices').hide('900');
      $('#short_answers').hide('900');
    });

    $('#question_correct_response_1').click(function() {
      $('#multiple_choices').hide('900');
      $('#short_answers').hide('900');
    });

    $('.short_answer').click(function() {
      $('#multiple_choices').hide();
      $('#short_answers').show('900');
      $('#short_answer').focus();
    });

    $('.multiple_choice').click(function() {
      $('#short_answers').hide();
      $('#multiple_choices').show('900');
      $('#choice_1').focus();
    });
  });

app/views/questions/_show.html.haml
- add_class = '' if local_assigns[:add_class].nil?

.card.replace-me{class: @question.slug}
  - if @already_taken
    = render partial: "questions/answer"
  - else
    .card-body

      -# %div
        / Question #{question_number} of #{@test.questions.length}:

      %h2.question-name
        = @question.name

      -if @question.description.present?
        %p
          = @question.description

      -if @question.image_url && !@question.image_url.blank?
        %div
          %img{:src => @question.image_url}

      %div{style: "padding:0;", id: "answer-box"}
        = form_with model: @question, method: :post, url: answer_test_question_path(@question.tst, @question), id: "answer-form" do |f|

          -if @question.kind == Question::TRUEFALSE
            = f.label :answer_true do
              = f.radio_button :answer, true, checked: false
              True

            = f.label :answer_false, {style: "display: block;"} do
              = f.radio_button :answer, false, checked: false
              False

          -elsif @question.kind == Question::SHORTANSWER
            %div{style: 'padding:10px 0;'}
              %input{type: 'text', name: 'short_answer', id: 'short_answer', autofocus: true}

          -else
            %div{style: 'padding:10px 0;'}
              -@question.choices.each_with_index do |choice, i|
                .form-check
                  %input.form-check-input{type: "radio", name: "choice_id", id: "choice_#{i}", value: choice.id}
                  %label.form-check-label{for: "choice_#{i}"}
                    = choice.name

          = submit_tag('Submit answer', id: 'submit_button', class: "btn btn-primary mt-20" )

          -# %div{:style => 'border: 1px solid red;'}
            / =link_to('comments', test_comments_path(@test.id, @test.to_param))

app/views/questions/edit.html.haml
%h1 Editing question
= render 'form'

app/views/questions/new.html.haml
.row.sign_in
  .col-12.col-sm-10.col-md-8.col-lg-6.offset-lg-2
    %h2.mt-20
      - if @test.questions.size == 0
        Add the first question
      -else
        New question

    = render 'form'

app/views/questions/show.html.haml
%p Question #{@question_number} of #{@test.questions.length}:
%h1= @question.name

%form#theForm
  %input{:type => 'hidden', :name => 'test_id', :value => "#{@test.id if @test}"}
  %input{:type => 'hidden', :name => 'take_id', :value => @take.id}
  %input{:type => 'hidden', :name => 'question_id', :value => "#{@question.id if @question}"}
  %input{:type => 'hidden', :name => 'question_number', :value => @question_number}
  %div{:style => "padding:15px 0;"}
  
    -# PARTIALS for all this shit.
    -if @question.kind == Question::TRUEFALSE
      %div
        %input#answer_true{:type => "radio", :name => "answer", :value => "true"}
        %label{:for => "answer_true", :style => "display:inline;"} true
      %input#answer_false{:type => "radio", :name => "answer", :value => "false"}
      %label{:for => "answer_false", :style => "display:inline;"} false
    -elsif @question.kind == Question::SHORTANSWER
      %input{:type => 'text', :name => 'short_answer'}
    -else
      %ul#choices
        -@question.choices.each do |choice|
          %li>
            %input{:type => "radio", :name => "choice_id", :value => choice.id}
            =choice.name
  =submit_tag 'Submit answer', :id => 'submit_button'
  -if @question_number < @test.questions.length
    (<a href="#" id="skip">skip</a> | <a href="#" id="stop">stop test</a>)

-if @question_number <= @test.questions.length

  :javascript
    $(document).ready(function(){

      $('#theForm').submit(function() {
        // validate. if valid...
        $.ajax({
          type: 'POST',
          url: '#{answer_path}',
          data: $('#theForm').serialize(),
          success: function(data) {
            // message, results, move to next question, whatever
            $('#question_pane').html(data);
            $('#question_pane').show('slide', {direction:'right'}, 600);
          },
          error: function(data) {
            alert('fail!');
          }
        });
        return false;
      });
      
      $('#skip').click(function() {
        $.get('#{question_path(@test.questions[@question_number], :test_id => @test.to_param, :qnum => (@question_number+1))}', function(data) {
          $('#question_pane').hide();
          $('#question_pane').html(data);
          $('#question_pane').show('slide', {direction:'right'}, 600);
        });
      });
    });