config/routes.rb
# better yet, just don't let people use . as part of a username.
# # by default rails considers '.' a separator, so override that
# module ActionController::Routing
#   SEPARATORS = %w( / ? )
# end

Rails.application.routes.draw do

  root to: "home#index"

  devise_for :users, controllers: { registration: 'registrations', session: 'sessions', invitations: 'users/invitations' }

  resources :tsts, path: :tests, as: :tests do
    member do
      get :publish
      get :enable
      get :disable
      get :comments
      get :results
    end
    resources :questions do
      collection do
        post :update_positions
      end
      member do
        post :answer
      end
    end
  end
  match 'tests/:test_id/invite', :to => 'devise/invitations#new', :as => 'test_invite', :via => :get
  match 'tests/:id/:permalink/results/:user_id/:take', :to => 'tsts#individual_results', :as => 'individual_test_results', :via => :get

  match 'people/:id/tests', :to => 'people#tests', :as => 'person_tests', :via => :get
  match 'people/:id/:slug', :to => 'people#show', :as => 'person', :via => :get

  match 'people/:id/follow/:object_type/:object_id', :to => 'people#follow', :as => 'follow', :via => :get
  match 'people/:id/unfollow/:object_type/:object_id', :to => 'people#unfollow', :as => 'unfollow', :via => :get

  # resources :users

  match 'embed/:id/:permalink', :to => 'tsts#show', :as => 'embed_test', :via => :get

  # # match 'tests/new', :to => 'tsts#new', :as => 'new_test', :via => :get
  # # match 'tests/:id/edit', :to => 'tsts#edit', :as => 'edit_test', :via => :get

  # match 'tests/:id/enable', :to => 'tsts#enable', :as => 'enable_test', :via => :get
  # match 'tests/:id/disable', :to => 'tsts#disable', :as => 'disable_test', :via => :get
  # match 'tests/:id/invite', :to => 'tsts#invite', :as => 'invite_test', :via => :get
  # # match 'tests/:test_id/questions/new', :to => 'questions#new', :as => 'invite_test', :via => :get
  #
  # match 'tests/:id/:slug', :to => 'tsts#show', :as => 'test', :via => :get
  #
  # # match 'tests/:id/:permalink/start', :to => 'tsts#show', :as => 'test', :via => :get
  #
  # # match 'tests/:id/:permalink', :to => 'tsts#destroy', :as => 'test', :via => :delete
  # # match 'tests/:id/:permalink/questions', :to => 'tsts#questions', :as => 'test_questions', :via => :get
  # # match 'tests/:id/:permalink/questions/:question_id/:qpermalink', :to => 'tsts#show', :as => 'test_question', :via => :get
  # # match 'tests/:id/:permalink/questions/:question_id', :to => 'tsts#show', :via => :get

  resources :results
  # resources :comments

  # match 'search', :to => 'search#results', :as => 'search', :via => :get
  # match 'search/:term', :to => 'search#results', :as => 'search_term', :via => :get

  # match 'tags/:id',:to => 'tags#show', :as => 'tag', :via => :get
  # resources :tags

  # match 'hide_promo', :to => 'home#hide_promo', :as => 'hide_promo', :via => :get

  match 'blohg', :to => 'home#blohg', :as => 'blohg', :via => :get
  match 'about', :to => 'home#about', :as => 'about', :via => :get
  match 'contact', :to => 'home#contact', :as => 'contact', :via => :get
  match 'terms', :to => 'home#terms', :as => 'terms', :via => :get
  match 'notes', :to => 'home#notes', :as => 'notes', :via => :get
  match 'deck', :to => 'home#deck', :as => 'deck', :via => :get
  match 'clear', :to => 'home#clear', :as => 'clear', :via => :get
  # match 'test', :to => 'home#test', :as => 'test'

end

app/controllers/people_controller.rb
# coding: utf-8

class PeopleController < ApplicationController

  def show
    # if current_user && !params[:dislay_name]
    #   flash.each {|key, msg| flash[key] = msg }
    #   redirect_to person_with_name_path(current_user.id, current_user.name) and return
    # end

    # @person = User.find(params[:id])
    # @title = "#{@person.name} - Testeroni"
    # @description = "#{@person.name}'s homepage on Testeroni."
    # @owner = true if user_signed_in? && @person.id == current_user.id

    @person = User.find(params[:id])
    @tests_created = @person.tsts
    @tests_taken = @person.unique_tests_taken
  end

  def tests
    @person = User.find(params[:id])
    @tests_created = @person.tsts
    @tests_taken = @person.unique_tests_taken
  end

  # match 'people/:id/follow/:object_type/:object_id', :to => 'people#follow', :as 'follow'
  def follow
    @person = User.find(params[:id])
    unless user_signed_in? && @person == current_user
      redirect_to root_path and return
    else
      followee = Object.const_get(params[:object_type]).find(params[:object_id])
      @person.follow(followee)

      render :partial => 'follow'
    end
  end

  # match 'people/:id/unfollow/:object_type/:object_id', :to => 'people#unfollow', :as 'follow'
  def unfollow
    @person = User.find(params[:id])
    redirect_to root_path and return unless user_signed_in? && @person == current_user

    if the_follow = Follow.where(["follow_type = ? AND follow_id = ?", params[:object_type], params[:object_id]])
      the_follow[0].delete
      render :partial => 'unfollow'
    else
      render :text => 'fail!'
    end
  end

end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/people/_follow.html.haml
= link_to 'unfollow', "#", onclick: "Tstrni.unfollow('#{current_user.id}', 'User', '#{@person.id}')", :style => 'font-size:1.2em;'

app/views/people/_unfollow.html.haml
=link_to_function('follow', "Tstrni.follow('#{current_user.id}', 'User', '#{@person.id}')", :class => 'green button sm', :style => 'font-size:1.2em;')

app/views/people/show.html.haml
.row.mt-50.ml-10
  .col-sm
    %h2
      #{@person.name} has created:

    - if @tests_created.present?
      %ul
        - @tests_created.each do |test|
          %li
            = link_to test.name, test_path(test)

    - else
      %i
        Nothing whatsoever!

  -# .col-6.col-md-10.col-lg-8
  .col-sm
    %h2
      #{@person.name} has taken:

    - if @tests_taken.present?
      %ul
        - @tests_taken.each do |test|
          %li
            = link_to test.name, test_path(test)

    - else
      %i
        Nothing whatsoever!

-#
  / %h1
  /   -if @owner
  /     Hi,
  /   = @person.name
  /   -if user_signed_in? && !@owner
  /     %span{:id => 'follow'}
  /       -#
  /         follow/unfollow here
  /         / -if current_user.is_following?(@person)
  /         /   =render :partial => 'follow'
  /         / -else
  /         /   =render :partial => 'unfollow'
  /
  /
  / %div{:style => 'float:left; width:550px; padding:10px 0 0 0; border:0px solid red;'}
  /   Activity from the people and tests you follow will eventually appear here
  /
  / %div{:style => 'float:left; width:420px; padding:10px 0 0 0; border:0px solid green;'}
  /
  /   -if user_signed_in? && @person.id == current_user.id
  /     %h3{:style => 'margin-bottom:20px;'}= link_to('Create a test!', new_test_path, :class => 'green button')
  /
  /   %p{:style => 'padding:20px 0 0 0; font-style:italic;'}tests created by #{@person.name}:
  /
  /   -if @person.tsts.blank?
  /     %p
  /       None, yet.
  /       -if user_signed_in? && @person.id == current_user.id
  /         Why don't you #{link_to 'create one', new_test_path}?
  /
  /   -else
  /     %ul.bulletless
  /       -@person.tsts.each do |t|
  /         %li{:style => 'padding:5px 0; margin:5px 0'}
  /           =link_to(t.name, test_path(t.id, t.to_param))
  /           -if t.user == current_user
  /             %span
  /               -unless t.published?
  /                 %em<
  /                   (unpublished)
  /               &nbsp;
  /               [
  /               -unless t.published?
  /                 =link_to('publish', publish_test_path(t))
  /                 |
  /               =link_to('results', results_test_path(t))
  /               |
  /               =link_to('edit', edit_test_path(t))
  /               |
  /               =link_to('delete', test_path(t.id, t.to_param), :method => :delete, :confirm => 'For real? This can never, ever be undone.')
  /               ]
  /
  /   %p{:style => 'padding:20px 0 0 0; font-style:italic;'}
  /     tests taken by #{@person.name}:
  /
  /   -if @person.takes.blank?
  /     %p None, yet, but there are lots of great tests waiting for you on the #{link_to('home page', root_path)}.
  /   -else
  /     %ul.bulletless
  /       -@person.takes.each do |t|
  /         -@test = Tst.find(t.tst_id)
  /         %li{:style => 'padding:5px 0; margin:5px 0'}
  /           =link_to @test.name, test_path(@test.id, @test.to_param)
  /           -if t.user == current_user
  /             &nbsp;
  /             %span
  /               [
  /               -#=link_to('your results', individual_test_results_url(@test.id, @test.to_param, current_user.username, t.id))
  /               =link_to('your results')
  /               |
  /               =link_to('overall results', results_test_path(@test))
  /               ]
  /
  / .clearfix
  / -#%p{:style => 'font-style:italic;'}tests created by #{@person.name}'s friends:
  /
  / -#%p{:style => 'font-style:italic;'}tests taken by #{@person.name}'s friends:

app/views/people/tests.html.haml
.row.mt-50.ml-10
  .col-sm
    %h2
      - if @person == current_user
        Tests you created
      - else
        #{@person.name} has created:

    - if @tests_created.present?
      %ul
        - @tests_created.each do |test|
          %li
            = link_to test.name, test_path(test)

    - else
      %i
        Nothing whatsoever!