config/routes.rb
# better yet, just don't let people use . as part of a username.
# # by default rails considers '.' a separator, so override that
# module ActionController::Routing
#   SEPARATORS = %w( / ? )
# end

Rails.application.routes.draw do

  root to: "home#index"

  devise_for :users, controllers: { registration: 'registrations', session: 'sessions', invitations: 'users/invitations' }

  resources :tsts, path: :tests, as: :tests do
    member do
      get :publish
      get :enable
      get :disable
      get :comments
      get :results
    end
    resources :questions do
      collection do
        post :update_positions
      end
      member do
        post :answer
      end
    end
  end
  match 'tests/:test_id/invite', :to => 'devise/invitations#new', :as => 'test_invite', :via => :get
  match 'tests/:id/:permalink/results/:user_id/:take', :to => 'tsts#individual_results', :as => 'individual_test_results', :via => :get

  match 'people/:id/tests', :to => 'people#tests', :as => 'person_tests', :via => :get
  match 'people/:id/:slug', :to => 'people#show', :as => 'person', :via => :get

  match 'people/:id/follow/:object_type/:object_id', :to => 'people#follow', :as => 'follow', :via => :get
  match 'people/:id/unfollow/:object_type/:object_id', :to => 'people#unfollow', :as => 'unfollow', :via => :get

  # resources :users

  match 'embed/:id/:permalink', :to => 'tsts#show', :as => 'embed_test', :via => :get

  # # match 'tests/new', :to => 'tsts#new', :as => 'new_test', :via => :get
  # # match 'tests/:id/edit', :to => 'tsts#edit', :as => 'edit_test', :via => :get

  # match 'tests/:id/enable', :to => 'tsts#enable', :as => 'enable_test', :via => :get
  # match 'tests/:id/disable', :to => 'tsts#disable', :as => 'disable_test', :via => :get
  # match 'tests/:id/invite', :to => 'tsts#invite', :as => 'invite_test', :via => :get
  # # match 'tests/:test_id/questions/new', :to => 'questions#new', :as => 'invite_test', :via => :get
  #
  # match 'tests/:id/:slug', :to => 'tsts#show', :as => 'test', :via => :get
  #
  # # match 'tests/:id/:permalink/start', :to => 'tsts#show', :as => 'test', :via => :get
  #
  # # match 'tests/:id/:permalink', :to => 'tsts#destroy', :as => 'test', :via => :delete
  # # match 'tests/:id/:permalink/questions', :to => 'tsts#questions', :as => 'test_questions', :via => :get
  # # match 'tests/:id/:permalink/questions/:question_id/:qpermalink', :to => 'tsts#show', :as => 'test_question', :via => :get
  # # match 'tests/:id/:permalink/questions/:question_id', :to => 'tsts#show', :via => :get

  resources :results
  # resources :comments

  # match 'search', :to => 'search#results', :as => 'search', :via => :get
  # match 'search/:term', :to => 'search#results', :as => 'search_term', :via => :get

  # match 'tags/:id',:to => 'tags#show', :as => 'tag', :via => :get
  # resources :tags

  # match 'hide_promo', :to => 'home#hide_promo', :as => 'hide_promo', :via => :get

  match 'blohg', :to => 'home#blohg', :as => 'blohg', :via => :get
  match 'about', :to => 'home#about', :as => 'about', :via => :get
  match 'contact', :to => 'home#contact', :as => 'contact', :via => :get
  match 'terms', :to => 'home#terms', :as => 'terms', :via => :get
  match 'notes', :to => 'home#notes', :as => 'notes', :via => :get
  match 'deck', :to => 'home#deck', :as => 'deck', :via => :get
  match 'clear', :to => 'home#clear', :as => 'clear', :via => :get
  # match 'test', :to => 'home#test', :as => 'test'

end

app/models/tst.rb
class Tst < ApplicationRecord

  ANYONE = 0
  JUSTME = 1

  ACTIVE = 0
  DISABLED = 1

  # https://github.com/elight/acts_as_commentable_with_threading
  # acts_as_commentable

  extend FriendlyId
  friendly_id :name, use: :slugged

  # acts_as_taggable

  attr_accessor :video_url

  belongs_to :user
  has_many :videos
  has_many :questions, -> { order('position, id') }
  has_many :responses
  has_many :takes

  validates :name, :presence => true
  validates :user_id, :presence => true, :numericality => true
  # validation to make sure tests don't have more than 100 questions?

  # scope :active, where(['status=?', Tst::ACTIVE])
  #
  # # scope :without_feed, joins('left outer join authors_feeds on authors.id=authors_feeds.author_id').where('authors_feeds.feed_id is null')
  # scope :non_empty, joins(:questions).where(["questions.id = id")
  #
  # # http://edgerails.info/articles/what-s-new-in-edge-rails/2010/02/23/the-skinny-on-scopes-formerly-named-scope/
  # # "Without the lambda the time that would be used in the query logic would be the time that the class was first evaluated, not the scope itself."
  # scope :published, lambda {
  #   where("tsts.published_at IS NOT NULL AND tsts.published_at <= ?", Time.zone.now)
  # }
  # scope :recently_published, active.non_empty.published.order("tsts.published_at DESC")

  def self.load_active_by_id(id)
    Tst.find_by_sql(['SELECT * FROM tsts WHERE id=? AND STATUS=? LIMIT 1', id, Tst::ACTIVE])[0]
  end

  def pause_points
    # pausePoints array is hashes of form {second => question_id}
    # {'testId' => id, 'pausePoints' => [{4 => 1}, {8 => 2}, {12 => 3}]}
    @pause_points = questions.map{|q| {q.id => q.pause_at}}
    {'testId' => id, 'pausePoints' => @pause_points}
  end

  def owned_by?(some_user)
    (user_id == some_user.id)
  end

  def active?
    (status == Tst::ACTIVE) ? true : false
  end

  def inactive?
    (status == Tst::DISABLED) ? true : false
  end

  def published?
    (published_at.nil?) ? false : true
  end

  def has_questions?
    (questions.size > 0)
  end

  # UPDATE: What even is this doing? its being used in the header for 'average score,' and it's
  # either misnamed, or doing the wrong thing.
  # TODO: This is horribly inefficient. Might eventually want to store a running total of correct answers
  # with each test, and update it as people take it. Would be better still if that update was batched:
  # keep the number needing to be updated in memory, write to the db every time it hits 10, or whatever.
  # Pain to do that with ruby :-(
  def percent_correct
    # @_percent_correct ||= begin
      @responses = Response.where(['tst_id=?', id])
      if @responses.size == 0
        0
      else
        @correct_responses = 0
        @responses.each do |r|
          @correct_responses += 1 if r.correct?
        end
        (((@correct_responses.to_f/@responses.size.to_f)*100)+0.5).to_i
      end
    # end
  end

  # get the percent_correct of every completed take of the test, average them
  def average_score
  end

  def grade
    @_grade ||= begin
      if percent_correct < 60
        'F'
      elsif percent_correct < 63
        'D-'
      elsif percent_correct < 67
        'D'
      elsif percent_correct < 70
        'D+'
      elsif percent_correct < 73
        'C-'
      elsif percent_correct < 77
        'C'
      elsif percent_correct < 80
        'C+'
      elsif percent_correct < 83
        'B-'
      elsif percent_correct < 87
        'B'
      elsif percent_correct < 90
        'B+'
      elsif percent_correct < 93
        'A-'
      elsif percent_correct < 97
        'A'
      else
        'A+'
      end
    end
  end

  def percent_correct_for(take)
  end

  def grade_for(take)
  end

end

app/controllers/tsts_controller.rb
# coding: utf-8

class TstsController < ApplicationController

  before_action :authenticate_user!, :except => [:index, :show, :comments]

  def index
    @tests = Tst.all
    @title = "Make and take surveys and tests on Testeroni"
    @description = "Make and take surveys and tests on Testeroni.com"
  end

  def show
    @test_page = true
    @test = Tst.friendly.find(params[:id])
    @owner = true if user_signed_in? && @test.owned_by?(current_user)
    @title = "#{@test.name} - Testeroni"
    @description = "'#{@test.name}' a test on Testeroni.com"
    @show_start_button = (@test.published? && @test.active?)
    session[:take_id] = nil
    # @comment = Comment.new(:commentable_type => @test.class, :commentable_id => @test.id)

    # if @test.questions.present?
    #   # @question = @test.questions.first
    #   @take = Take.new( :tst_id => @test.id,
    #                     :user_id => (user_signed_in?) ? current_user.id : nil,
    #                     :started_at => Time.now,
    #                     :questions_answered => 0,
    #                     :questions_correct => 0,
    #                     :question_order => @test.questions.pluck(:id) )
    #
    # end

    # if @take.present?
    #   if user_signed_in?
    #     @take.save
    #   else
    #     session[:take] = @take.sessionize
    #   end
    # end

    # if @test.questions.present? && @question_ids.size > 1
    #   @next_question = Question.find(@question_ids[1])
    #   @next_question_url = question_path(@next_question, :test_id => @test.to_param, :question_number => 2)
    # end

    # render :layout => 'embed' if request.path =~ /embed/
  end

  def new
    # god there are better ways to do this
    redirect_to root_path and return unless user_signed_in?

    @test = Tst.new(:contributors => Tst::ANYONE)

    @title = "Create a new test or survey on Testeroni"
    @description = "Create a new test or survey on Testeroni.com"
  end

  def edit
    @test = Tst.friendly.find(params[:id])
    redirect_to root_path and return unless user_signed_in? && @test.user == current_user
  end

  def create
    @test = Tst.new(tst_params)
    @test.status = Tst::ACTIVE
    @test.user = current_user
    redirect_to root_path and return unless user_signed_in? && @test.user == current_user

    if @test.video_url
      @video = Video.new
      @video.url = @test.video_url
      @video.tst = @test
      # enter video name? get it from YouTube?

      @video.provider_id = @video.get_provider_id_from_url
      @video.save
    end

    out = @test.save

    if @test.save
      record_activity(current_user, Activity::CREATE, @test)
      # redirect_to( new_question_path(:test_id => @test.id), :notice => 'Test was successfully created.')
      redirect_to new_test_question_path(@test), notice: "Test was successfully created, now add some questions!"
    else
      render :action => "new"
    end
  end

  def publish
    @test = Tst.friendly.find(params[:id])

    # put auth above this somewehre
    redirect_to root_path and return unless user_signed_in? && @test.user == current_user

    @test.published_at = Time.now

    if @test.save
      @owner = true if user_signed_in? && @test.owned_by?(current_user)
      @title = "#{@test.name} - Testeroni"
      @description = "'#{@test.name}' a test on Testeroni.com"
      @comment = Comment.new(:commentable_type => @test.class, :commentable_id => @test.id)
      @question_number = 1
      # is there a way to get the question_number without having to loop?
      if params[:question_id]
        @question = Question.find(params[:question_id])
        @test.questions.each_with_index do |q, i|
          if q.id == @question.id
            @question_number = i+1
            break
          end
        end
      end
      # @next_question_url = question_path(@test.questions[(@question_number-1)], :test_id => @test.to_param, :question_number => @question_number)
      flash[:notice] = 'Congratulations, your test has been published and can now be taken.'
      # redirect_to test_path @test
      redirect_to new_user_invitation_path

    else
      flash[:alert] = 'There was a problem publishing.'
      redirect_back(fallback_location: root_path)
    end
  end

  def enable
    @test = Tst.friendly.find(params[:id])
    redirect_to root_path and return unless user_signed_in? && @test.user == current_user

    @test.status = Tst::ACTIVE
    @test.save
    redirect_to :back
  end

  def disable
    @test = Tst.friendly.find(params[:id])
    redirect_to root_path and return unless user_signed_in? && @test.user == current_user

    @test.status = Tst::DISABLED
    @test.save
    redirect_to :back
  end

  def invite
    @test = Tst.friendly.find(params[:id])
    redirect_to root_path and return unless user_signed_in? && @test.user == current_user

    if params[:invite].blank?
      flash[:notice] = "Please select people to invite and resubmit."
      redirect_to test_path(@test.id, @test.to_param)
    else
      if @token = current_user.facebook_token
        @graph = Koala::Facebook::GraphAPI.new(@token)
        params[:invite].each do |i|
          # WANT to send message (email via fb, or internal fb messages, doesn't matter), not post to walls. doesn't look like graph api supports that, though :-(
          # @graph.put_wall_post("has invited you to take a test:", {:name => @Tst.name, :link => test_url(@test)}, "me")
        end
      end
    end
  end

  def individual_results
    @test = Tst.load_active_by_id(params[:id])
    #redirect_to root_path and return unless user_signed_in? && @test.user == current_user
    @user = User.find(params[:user_id])
    @take = Take.find(params[:take])

  end

  def results
    @test = Tst.load_active_by_id(params[:id])
  end

  def questions
    @test = Tst.load_active_by_id(params[:id])
  end

  # def comments
  #   @test = Tst.load_active_by_id(params[:id])
  #   @title = "Comments on #{@test.name} - Testeroni"
  #   @description = "Comments on '#{@test.name}' a test on Testeroni.com"
  #
  #   @comment = Comment.new(:commentable_type => @test.class, :commentable_id => @test.id)
  # end

  def update
    @test = Tst.friendly.find(params[:id])
    redirect_to root_path and return unless user_signed_in? && @test.user == current_user

    if @test.update(tst_params)
      redirect_to(test_path(@test), :notice => 'Test was successfully updated.')
    else
      render :action => "edit"
    end
  end

  def destroy
    @test = Tst.friendly.find(params[:id])
    redirect_to root_path and return unless user_signed_in? && @test.user == current_user

    @test.destroy
    redirect_to(:back, :notice => 'test DESTROYED!')
  end

  private

    # Never trust parameters from the scary internet, only allow the white list through.
    def tst_params
      params.require(:tst).permit(:name, :description, :status, :contributors)
    end

end

app/helpers/tsts_helper.rb
# coding: utf-8

module TstsHelper
end

app/views/tsts/_form.html.haml
= form_for( @test, {url: form_url} ) do |f|

  -if @test.errors.any?
    #error_explanation
      %h2 #{pluralize(@test.errors.count, "error")} prohibited this test from being saved:
      %ul
        -@test.errors.full_messages.each do |msg|
          %li= msg


  .field.mt-20
    =f.label :name, 'Title'
    =f.text_field :name, autofocus: true, class: 'form-control'

  .field.mt-20
    =f.label :description, 'Description'
    =f.text_area :description, class: 'form-control'

    -#%h6{:style => 'padding:0 0 5px 0;'} Questions can be added to this test by:
    -#%div{:style => 'padding:0 0 5px 0;'}
      =f.radio_button :contributors, Tst::ANYONE
      =f.label :contributors_1, 'Anyone, anyone at all', :style => 'display:inline;'
    -#%div
      =f.radio_button :contributors, Tst::JUSTME
      =f.label :contributors_2, 'Just me', :style => 'display:inline;'
    -#
      / %p
      /   =f.label :tag_list, 'Tags (comma separated)'
      /   =f.text_field :tag_list

    -#if @test.id.blank?
      / .field.mt-20
      /   =f.label :video_url, 'Video (add an optional YouTube URL)'
      /   =f.text_field :video_url, class: 'form-control'

    -unless @test.id.blank?
      %p
        Video associated with this test:
      -if @test.videos.blank?
        %p{:style => "font-style:italic;"}
          None, now.
      -else
        %ul
          -@test.videos.each do |video|
            %li="video: #{video.class}; #{video.name}"

  .actions
    = f.submit (@test.id.blank? ? "Create test" : "Edit test"), class: 'btn btn-outline-dark mr-10'

    =# link_to 'cancel', test_path(@test)

app/views/tsts/_header.html.haml
%h1.test-hed.mt-0.pt-0
  - if @test_page
    = @test.name
  - else
    = link_to @test.name, test_path(@test)

%div
  Created #{time_ago_in_words(@test.created_at)} ago by #{profile_link(@test.user)}

.mb-10
  = pluralize(@test.questions.size, 'question')
  · taken
  = pluralize(@test.takes.size, 'time')

  -if @test.takes.size > 0
    ·
    average score #{@test.percent_correct}

  -# =link_to(pluralize(@test.root_comments.size, 'comment'), test_comments_path(@test.id, @test.to_param), :id => 'question_comment_link')

  - if @test_page
    %div
      -if @test.published?
        -if @test.active?
          / ·
          / = link_to 'share', "#", onclick: "$('#share_tools').toggle()"
          / ·
          / = link_to 'embed', "#", onclick: "$('#embed_header').toggle()"
          -if @owner
            =link_to('Disable', disable_test_path(@test))
        -elsif @owner
          =link_to('Enable', enable_test_path(@test))
      -else
        -if @owner
          ·
          %em
            This test is not yet published, only you can see it.
            = link_to 'publish', publish_test_path(@test), class: "btn btn-xs btn-secondary ml-20"

      -if @owner
        = edit_link(edit_test_path(@test))
        = trash_link(test_path(@test), "Are you sure you want to delete the test #{@test.name}?")

  -#
    / %div{:id => 'share_tools', :style => 'display:none; width:520px;'}
    /   %label{:for => 'share_link'} Link to this test
    /   %input{:id => 'share_link', :type => 'text', :value => test_url(@test.id, @test.to_param)}
    /   %p
    /     %div{:style => 'float:right;'}
    /       =link_to '[x] close', "#", onclick: "$('#share_tools').toggle()"
    /     fb like, tweet, txt, mail, etc.

    / %div{:id => 'embed_header', :style => 'display:none; padding-top:10px; width:520px;'}
    /   %textarea{:id => 'embed_test', :style => 'height:50px;'}= embed_code(@test)
    /   .caption
    /     After making your selection, copy and paste the embed code above. The code changes based on your selection.
    /     %div{:style => 'padding:5px 0 0 0; float:right;'}
    /       = link_to '[x] close', "#", onclick: "$('#embed_header').toggle()"

- if @test.description.present?
  %div
    = @test.description

app/views/tsts/_invite.html.haml
.mt-20

  Invite friends to take this test!

  = form_for :user, :as => "User", :url => invitation_path(:user), :html => {:method => :post} do |f|
    -# = devise_error_messages!
    - User.invite_key_fields.each do |field|

      .field.mt-20
        -# =f.text_field :name, autofocus: true, class: 'form-control'
        = f.text_field field, class: 'form-control', placeholder: "Emails, comma separated."

    = f.submit t("devise.invitations.new.submit_button"), class: 'btn btn-outline-dark mt-20 mb-30'

app/views/tsts/aggregated_results.html.haml
=render(:partial => 'tsts/header')

%p Overall results of the test

app/views/tsts/comments.html.haml
=render(:partial => 'tsts/header')

-if signed_in?
  =render :partial => 'application/comments', :locals => {:commentable => @test, :comment => @comment, :comments => @test.root_comments}
-else
  Please
  = link_to_function('sign up', "Tstrni.viewSignup()")
  or
  = link_to_function('sign in', "Tstrni.viewLogin()")
  -#!= "Please #{link_to('sign in', new_user_session_path)} or #{link_to('sign up', new_user_registration_path)} to post comments."

app/views/tsts/edit.html.haml
.row.sign_in
  .col-12.col-sm-10.col-md-8.col-lg-6.offset-lg-2
    %h2
      Editing
      %em
        = link_to @test.name, test_path(@test)

    = render partial: 'form', locals: {form_url: test_path(@test)}

    .questions
      %h4{:style => 'padding:40px 0 5px 0;'}>
        Questions
        = link_to 'Add question', new_test_question_path(@test), class: "btn btn-primary ml-10 mr-10 btn-sm"
        %span
          = link_to 'Done', test_path(@test)

      -unless @test.questions.blank?
        -# previous data-update-=url: update_positions_lists_items_path(@list)
        - question_attributes = { class: 'sortable-items', 'data-role': 'sortable_items', 'data-update-url': update_positions_test_questions_path(@test) }

        .list-group{ question_attributes }
          -@test.questions.each do |question|
            .list-group-item.list-group-item-action.has-hover-items.sortable-item{ 'data-item-id': question.id }
              .float-right
                %span.hover-item
                  = edit_link(edit_test_question_path(@test, question))
                  = trash_link(test_question_path(@test, question), "Are you sure you want to delete the question #{question.name}?")

              = question.name

              -unless question.description.blank?
                %div
                  = question.description

app/views/tsts/index.html.erb
<h1>Listing tests</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tests.each do |test| %>
  <tr>
    <td><%= link_to 'Show', test %></td>
    <td><%= link_to 'Edit', edit_test_path(test) %></td>
    <td><%= link_to 'Destroy', test, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Test', new_test_path %>

app/views/tsts/individual_results.html.haml
=render(:partial => 'tsts/header')

%p{:style => 'padding-bottom:20px;'}
  Test results for: #{@user.name}, taken #{@take.finished_at}

%ul.bulletless

  - if @take
    %ol
      -#-@take.responses.each do |r|
      -@test.questions.each do |question|
        %li{:style => 'padding-bottom:10px;'}
          %div
            Question:
            %em= question.name
          -if question.image_url
            %div
              %img{:src => question.image_url}
          -r = Response.where(['take_id=? AND question_id=?', @take.id, question.id]).first
          -if r.nil?
            %div
              %em No response
          -else
            %div
              your answer:
              -if r.answer == true
                true
              -elsif r.answer == false
                false
              -elsif r.question.kind == Question::SHORTANSWER
                = r.name
              -else
                = r.choice.name
            -if r.correct
              %strong
                CORRECT!
            -else
              %strong
                Sorry, wrong.
              The correct answer is:
              -if r.question.kind == Question::TRUEFALSE
                =(r.question.correct_response == 1) ? 'true' : 'false'
              -else
                =r.question.correct_choice.name

app/views/tsts/invite.html.haml
%h3 Thanks, invites were sent

%p back to
%h2
  = link_to(@test.name, test_path(@test))

%p Things to do now:

%ul.bulletless
  %li= link_to('Create another test', new_test_path)
  %li= link_to('View the results of this test (needs an rss feed)', test_results_path(@test))
  %li Ask if they want to tweet it, send invite emails, or post to fb wall
  

app/views/tsts/new.html.haml
.row.sign_in
  .col-12.col-sm-10.col-md-8.col-lg-6.offset-lg-2
    %h2
      Create a test

    = render partial: 'form', locals: {form_url: tests_path}

app/views/tsts/publish.html.haml
/ =render(:partial => 'tsts/header')
/ 
/ %p You just published the test
/ %h1= link_to(@test.name, test_path(@test.id, @test.to_param))
/ 
/ -#
/   / %p{:style => 'padding:10px 0;'} But nobody knows about it yet. Invite your friends to take the test.
/   / 
/   / %div{:style => 'height:320px;'}
/   /   %div{:style => 'float:left; width:38%'}
/   /     = form_tag(invite_test_url(@test)) do
/   /       %ul.bulletless.scrollable
/   /         - @friends.each do |f|
/   /           %li
/   /             %input{:type => 'checkbox', :name => 'invite[]', :value => f['id']}= f['name']
/   /       %input{:type => 'submit', :value => 'Invite your friends to take the test!'}
/   /   
/   /   %div{:style => 'float:right; width:58%;'}
/   /     %textarea{:style => 'width:100%'} Check the box next to the name of each friend you want to message about this test.
/       
/ %ul.bulletless{:style => 'padding-top:20px;'}
/   %li= link_to('Create another test', new_test_path)
/   %li= link_to('View the results of this test (needs an rss feed)', test_results_path(@test.id, @test.to_param))
/   %li Ask if they want to tweet it, send invite emails, or post to fb wall (only offer if they're fb connected, ajax a call to the graph api)

app/views/tsts/questions.html.haml
all the questions on the test, with some data about each, and prominent 'take the test' buttons.

app/views/tsts/results.html.haml
=render(:partial => 'tsts/header')

%p
  aggregated results for the whole test (number of takers, average grade, date created, users taken by)
  
%p
  aggregated results for each question (% of taker who got it right, etc.)

app/views/tsts/show.html.haml
.row.mt-10
  .col-12.col-md-10.offset-md-1
    =render partial: 'tsts/header'

    -#unless @test.videos.blank?
      / %div{style: 'float:left; border: 0px solid red; padding-right:20px;'}
      /   -@test.videos.each_with_index do |v,i|
      /     %div{id: "ytplayer_#{i}"}

          -#%div
            / =link_to_function('play', "Tstrni.play('ytplayer_#{i}')")
            / &#183;
            / =link_to_function('playAndPause', "Tstrni.playAndPause('ytplayer_#{i}')")
            / &#183;
            / =link_to_function('pause', "Tstrni.pause('ytplayer_#{i}')")
            / &#183;
            / =link_to_function('stop', "Tstrni.stop('ytplayer_#{i}')")
            / &#183;

          // :javascript
          //   $(document).ready(function(){
          //
          //     // get stop points from test (tst#stop_points), put in an object in the Tstrni object
          //     // data structure: {'testId':3, 'pausePoints':[{stopAtSecond: displayQuestionId}]}
          //     // Tstrni.pausePointsForTest = #{@test.pause_points.to_json}
          //
          //     var params = { allowScriptAccess: "always" };
          //     swfobject.embedSWF("http://www.youtube.com/v/#{v.provider_id}&enablejsapi=1&playerapiid=ytplayer_#{i}", "ytplayer_#{i}", "480", "385", "8", null, null, params);
          //   });

    -if @show_start_button
      .mt-30
        - if user_signed_in?
          = link_to 'Take the test!', test_question_path(@test, @test.questions.first), class: "btn btn-secondary btn-lg mb-10 mr-10"
          or #{link_to "invite friends", new_user_invitation_path}.
        -else
          = link_to 'Take the test!', new_user_registration_path, class: "btn btn-secondary btn-lg mb-10"

    .questions
      -if @owner
        -if !@test.has_questions?
          = link_to 'Add the first question', new_test_question_path(@test), class: "btn btn-secondary btn-lg mb-10 mt-30"

      -if @test.has_questions? && @test.published? && @test.active?
        - @test.questions.each_with_index do |q, i|
          - if @question == q
            = render partial: 'questions/show', locals: {add_class: 'active'}
          -#
            / - else
            /   .card
            /     .card-body
            /       #{q.name}

        -#=render :partial => 'shared/comments', :locals => {:commentable => @test, :comment => @comment, :comments => @test.root_comments}

      -elsif @test.inactive?
        %em
          Sorry, this test is currently inactive.

    .clearfix