config/routes.rb
# better yet, just don't let people use . as part of a username.
# # by default rails considers '.' a separator, so override that
# module ActionController::Routing
#   SEPARATORS = %w( / ? )
# end

Rails.application.routes.draw do

  root to: "home#index"

  devise_for :users, controllers: { registration: 'registrations', session: 'sessions', invitations: 'users/invitations' }

  resources :tsts, path: :tests, as: :tests do
    member do
      get :publish
      get :enable
      get :disable
      get :comments
      get :results
    end
    resources :questions do
      collection do
        post :update_positions
      end
      member do
        post :answer
      end
    end
  end
  match 'tests/:test_id/invite', :to => 'devise/invitations#new', :as => 'test_invite', :via => :get
  match 'tests/:id/:permalink/results/:user_id/:take', :to => 'tsts#individual_results', :as => 'individual_test_results', :via => :get

  match 'people/:id/tests', :to => 'people#tests', :as => 'person_tests', :via => :get
  match 'people/:id/:slug', :to => 'people#show', :as => 'person', :via => :get

  match 'people/:id/follow/:object_type/:object_id', :to => 'people#follow', :as => 'follow', :via => :get
  match 'people/:id/unfollow/:object_type/:object_id', :to => 'people#unfollow', :as => 'unfollow', :via => :get

  # resources :users

  match 'embed/:id/:permalink', :to => 'tsts#show', :as => 'embed_test', :via => :get

  # # match 'tests/new', :to => 'tsts#new', :as => 'new_test', :via => :get
  # # match 'tests/:id/edit', :to => 'tsts#edit', :as => 'edit_test', :via => :get

  # match 'tests/:id/enable', :to => 'tsts#enable', :as => 'enable_test', :via => :get
  # match 'tests/:id/disable', :to => 'tsts#disable', :as => 'disable_test', :via => :get
  # match 'tests/:id/invite', :to => 'tsts#invite', :as => 'invite_test', :via => :get
  # # match 'tests/:test_id/questions/new', :to => 'questions#new', :as => 'invite_test', :via => :get
  #
  # match 'tests/:id/:slug', :to => 'tsts#show', :as => 'test', :via => :get
  #
  # # match 'tests/:id/:permalink/start', :to => 'tsts#show', :as => 'test', :via => :get
  #
  # # match 'tests/:id/:permalink', :to => 'tsts#destroy', :as => 'test', :via => :delete
  # # match 'tests/:id/:permalink/questions', :to => 'tsts#questions', :as => 'test_questions', :via => :get
  # # match 'tests/:id/:permalink/questions/:question_id/:qpermalink', :to => 'tsts#show', :as => 'test_question', :via => :get
  # # match 'tests/:id/:permalink/questions/:question_id', :to => 'tsts#show', :via => :get

  resources :results
  # resources :comments

  # match 'search', :to => 'search#results', :as => 'search', :via => :get
  # match 'search/:term', :to => 'search#results', :as => 'search_term', :via => :get

  # match 'tags/:id',:to => 'tags#show', :as => 'tag', :via => :get
  # resources :tags

  # match 'hide_promo', :to => 'home#hide_promo', :as => 'hide_promo', :via => :get

  match 'blohg', :to => 'home#blohg', :as => 'blohg', :via => :get
  match 'about', :to => 'home#about', :as => 'about', :via => :get
  match 'contact', :to => 'home#contact', :as => 'contact', :via => :get
  match 'terms', :to => 'home#terms', :as => 'terms', :via => :get
  match 'notes', :to => 'home#notes', :as => 'notes', :via => :get
  match 'deck', :to => 'home#deck', :as => 'deck', :via => :get
  match 'clear', :to => 'home#clear', :as => 'clear', :via => :get
  # match 'test', :to => 'home#test', :as => 'test'

end

app/views/layouts/_footer.html.haml
%footer.footer.border-top.text-right
  .container.mb-20
    =link_to('about', about_path)
    ·
    =link_to('contact', contact_path)

app/views/layouts/_head.html.haml
%head
  %meta{:charset => 'utf-8'}
  %meta{'http-equiv' => 'X-UA-Compatible', :content => 'IE=edge,chrome=1'}

  %title= @title ||= 'Testeroni'

  %meta{:name => 'description', :content => 'A platform for casual and fun learning. Make your own tests and share, take . Answers can be multiple choice or true/false, and tests can be shared and embedded.'}
  %meta{:name => 'viewport', :content => 'width=device-width, initial-scale=1.0'}

  %link{href: "https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css", rel: "stylesheet", integrity: "sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS", crossorigin: "anonymous"}

  =javascript_include_tag('https://use.typekit.com/jxe0dey.js')
  %script{:type => "text/javascript"} try{Typekit.load();}catch(e){}
  =javascript_include_tag('https://www.google.com/jsapi?key=ABQIAAAAnohM6sqTs6drjmtNvnIyhBQX4KEUxjBL_ZDpzqYIgEd3Cy73NxTBwcj0akdZnV23u8exfLERTanWEw')

  %link{href: "https://use.fontawesome.com/releases/v5.7.1/css/all.css", crossorigin: "anonymous", integrity: "sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr", rel: "stylesheet"}

  %script{:src => "https://code.jquery.com/jquery-3.3.1.min.js", :crossorigin => "anonymous", :integrity => "sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="}

  %script{:src => "https://code.jquery.com/ui/1.12.1/jquery-ui.min.js", :crossorigin => "anonymous", :integrity => "sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU="}

  <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/lodash.js/0.10.0/lodash.min.js"></script>

  %script{src: "https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js", integrity: "sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k", crossorigin: "anonymous"}

  = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
  = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'

  <link href="https://fonts.googleapis.com/css?family=Ubuntu:500" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Playfair+Display" rel="stylesheet">

  :javascript
    // if(typeof google === 'undefined') {
    //   document.write('<script type="text/javascript" src = "/javascripts/jquery.min.js"><\/script>');
    //   document.write('<script type="text/javascript" src = "/javascripts/jquery-ui.min.js"><\/script>');
    //   document.write('<script type="text/javascript" src = "/javascripts/swfobject.js"><\/script>');
    // } else {
    //   google.load("jquery", "1.5.1");
    //   google.load("jqueryui", "1.8.11");
    //   google.load("swfobject", "2.2");
    // }

    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-20111813-1']);
    _gaq.push(['_trackPageview']);

    (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();

  -# for the stackoverflow-based text editor.
  -# combine all these in prod, plus the shit at the bottom of this template too
    / = javascript_include_tag("/wmd/wmd.js")
    / = javascript_include_tag("/wmd/showdown.js")
    / = javascript_include_tag '/javascripts/jquery.lightbox_me.js'
    / = javascript_include_tag('/javascripts/jquery.ba-bbq.min.js')
    / = javascript_include_tag('/javascripts/tstrni.js')

  -#= stylesheet_link_tag("/stylesheets/testeroni.css")

  =csrf_meta_tag

app/views/layouts/_nav.html.haml
%nav.top-nav.navbar.navbar-expand-sm.navbar-light
  %a.navbar-brand#logotype{:href => "/"}
    Testeroni

  -# burger
  %button.navbar-toggler{"aria-controls": "navbar-dropdown", "aria-expanded": "false", "aria-label": "Toggle navigation", "data-target": "#navbar-dropdown", "data-toggle": "collapse", type: "button"}
    %span.navbar-toggler-icon

  #navbar-dropdown.collapse.navbar-collapse.mb-0
    %ul.navbar-nav.ml-auto

      - if user_signed_in?
        %li.nav-item.mr-20
          = link_to 'Create a test', new_test_url, class: "btn btn-primary"

        %li.nav-item
          = link_to 'Home', root_path, class: "nav-link"
        %li.nav-item
          = link_to 'My tests', person_tests_path(current_user.id), class: "nav-link"

        %li.nav-item.dropdown
          %a#profile-dropdown.nav-link.dropdown-toggle{"href" => "", "aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown"}
            = current_user.name

          .dropdown-menu.dropdown-menu-right{"aria-labelledby" => "profile-dropdown"}
            - if true #current_user.is_admin?
              = link_to 'Admin', "#", class: 'admin dropdown-item'
            = link_to 'Profile', person_path(current_user.id, current_user.to_param), class: 'dropdown-item'
            = link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'dropdown-item'

      - else
        %li.nav-item
          %b
            = link_to 'Sign up', new_user_registration_path, class: 'nav-link'
        %li.nav-item
          = link_to 'Sign in', new_user_session_path, class: 'nav-link'

app/views/layouts/application.html.haml
!!! 5
%html
  = render partial: "layouts/head"

  %body
    -# = render partial: "application/promo"
    = render partial: "layouts/nav"

    .container-fluid
      =render(:partial => 'application/flash', :locals => {:flash => flash})

      =yield

    = render partial: "layouts/footer"

    -# if @promo
      // :javascript
      //   google.setOnLoadCallback(function() {
      //     //setTimeout('Tstrni.promo.show', 500);
      //     setTimeout('Tstrni.show_promo()', 1500);
      //   })

    :javascript

      var _gaq = [['_setAccount', 'UA-XXXXX-X'], ['_trackPageview']];
      (function(d, t) {
        var g = d.createElement(t),
        s = d.getElementsByTagName(t)[0];
        g.async = true;
        g.src = ('https:' == location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        s.parentNode.insertBefore(g, s);
      })(document, 'script');

      $(document).ready(function() {

        $('#twitter-link').click(function() {
          var reg = /^([A-Za-z0-9_\-\.])+\@([A-Za-z0-9_\-\.])+\.([A-Za-z]{2,4})$/;
          if(reg.test($('#email').val()) == false) {
            alert('please enter a valid email address.');
            return false;
          } else {
            document.cookie='email=' + $('#email').val() + '; path=/\;';
          }
        });

        $('#use_email').click(function() {
          $('.account').toggle();
          $('#user_username').focus();
        });

      });

app/views/layouts/embed.html.haml
!!! 5
%html
  %head
    %meta{:charset => 'utf-8'}
    %meta{'http-equiv' => 'X-UA-Compatible', :content => 'IE=edge,chrome=1'}

    %title= @title ||= 'Testeroni'

    %meta{:name => 'description', :content => 'A platform for casual and fun learning. Make and take tests your own tests. Answers can be multiple choice or true/false, and tests can be shared and embedded.'}
    %meta{:name => 'viewport', :content => 'width=device-width, initial-scale=1.0'}

    =stylesheet_link_tag(:flutie, 'testeroni', 'https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.7/themes/accordion/jquery-ui.css',  :cache => true)

    =javascript_include_tag('http://use.typekit.com/jxe0dey.js')
    %script{:type => "text/javascript"} try{Typekit.load();}catch(e){}
    =javascript_include_tag('http://www.google.com/jsapi?key=ABQIAAAAnohM6sqTs6drjmtNvnIyhBQX4KEUxjBL_ZDpzqYIgEd3Cy73NxTBwcj0akdZnV23u8exfLERTanWEw')
    :javascript
      google.load("jquery", "1.4.4");
      google.load("jqueryui", "1.8.7");

      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-20111813-1']);
      _gaq.push(['_trackPageview']);

      (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();

    =javascript_include_tag("/wmd/wmd.js")
    =javascript_include_tag("/wmd/showdown.js")
    =csrf_meta_tag

  %body

    #container{:style => 'width:630px;'}
      =render(:partial => 'application/flash', :locals => {:flash => flash})

      =yield

    -#
      #foot-wrap
        #footer
          =link_to('about', about_path)
          &#183;
          =link_to('contact', contact_path)
          &#183;
          %a.twitter-share-button{:href => "http://twitter.com/share", 'data-count' => "none", 'data-via' => "besteroni"} Tweet
          %script{:type => "text/javascript", :src => "http://platform.twitter.com/widgets.js"}

    =javascript_include_tag('rails')
    =javascript_include_tag('tstrni.js')

    :javascript

      var _gaq = [['_setAccount', 'UA-XXXXX-X'], ['_trackPageview']];
      (function(d, t) {
        var g = d.createElement(t),
        s = d.getElementsByTagName(t)[0];
        g.async = true;
        g.src = ('https:' == location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        s.parentNode.insertBefore(g, s);
      })(document, 'script');